### ISSUE TITLE
libarchive

### ISSUE THREAD

**Issue by ouhouhsami** [Legilibre/legi.py#14]
Bonjour, 

j'ai un petit pb avec legi.py, ou plutôt, libarchive sur mon Mac OS X 10.12.3, avec python 3.5

```python -m legi.tar2sqlite legi.sqlite ./tarballs
read format "7zip" is not supported
read format "rar" is not supported
read format "cab" is not supported
read format "lha" is not supported
read filter "none" is not supported
read filter "xz" is not supported
read filter "bzip2" is not supported
read filter "grzip" is not supported
read filter "rpm" is not supported
read filter "compress" is not supported
read filter "gzip" is not supported
read filter "uu" is not supported
read filter "lrzip" is not supported
read filter "lzma" is not supported
read filter "lzip" is not supported
read filter "all" is not supported
read filter "lzop" is not supported
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/g/s/pro/dev/legi.py/legi/tar2sqlite.py", line 13, in <module>
    import libarchive
  File "/Users/g/s/.virtualenvs/legi/lib/python3.5/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/g/s/.virtualenvs/legi/lib/python3.5/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Users/g/s/.virtualenvs/legi/lib/python3.5/site-packages/libarchive/ffi.py", line 167, in <module>
    c_int, check_int)
  File "/Users/g/s/.virtualenvs/legi/lib/python3.5/site-packages/libarchive/ffi.py", line 92, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 360, in __getattr__
    func = self.__getitem__(name)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/ctypes/__init__.py", line 365, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7ff6d9724f50, archive_read_open_filename_w): symbol not found
```

Peut-être que cette stack trace vous parle ? Il semble que libarchive (installé par brew) et le pypi libarchive-c "communique" pas bien ?

Merci,

**Comment by Changaco** [comment]
Quel est le numéro de version de la libarchive installée ?

**Comment by ouhouhsami** [comment]
Alors voici la version :  
libarchive: stable 3.3.1 (bottled) [keg-only]
Multi-format archive and compression library

**Comment by Changaco** [comment]
Pareil, le problème ne vient donc pas de là. Il est clair que la libarchive que le module python essaye d'utiliser est incomplète, même si le programme ne plantait pas sur `read_open_filename_w` il manque de toute façon le filtre `gzip` donc legi.py ne pourrait pas fonctionner.

**Comment by ouhouhsami** [comment]
Donc 2 choses : voir si libarchive qui est utilisé est la bonne et la compiler avec le support gzip.
Parce que j'ai installé libarchive avec homebrew, et que "si ça se trouve", le wrapper python utilise celui présent pas défaut sur mac os X.

**Comment by Changaco** [comment]
Exactement. Tu peux contrôler quelle libarchive est utilisée en mettant le chemin de celle que tu veux dans la variable d'environnement `LIBARCHIVE`.

**Comment by ouhouhsami** [comment]
Alors pour les utilisateurs de MacOS X, et qui installent libarchive avec brew, il faut bien positionner le libarchive appelé par libarchive-c (dans requirements de ce projet)

```export LIBARCHIVE=/usr/local/opt/libarchive/lib/libarchive.13.dylib```

merci !

**Comment by ouhouhsami** [comment]
Petites remarques, à la fin de la création de sqlite, j'ai
```
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.5.2_3/Frameworks/Python.framework/Versions/3.5/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/g/s/pro/dev/legi.py/legi/tar2sqlite.py", line 511, in <module>
    main()
  File "/Users/g/s/pro/dev/legi.py/legi/tar2sqlite.py", line 506, in main
    factorize(db)
TypeError: main() takes 0 positional arguments but 1 was given
```

**Comment by Changaco** [comment]
Oups. Je vais corriger ça.

**Comment by fpagnoux** [comment]
> Alors pour les utilisateurs de MacOS X, et qui installent libarchive avec brew, il faut bien positionner le libarchive appelé par libarchive-c (dans requirements de ce projet)
> 
> export LIBARCHIVE=/usr/local/opt/libarchive/lib/libarchive.13.dylib
> 

@Changaco: est-ce que cette information, cruciale pour pouvoir utiliser `legi.py` sous Mac pourrait être ajoutée à la doc? Merci!
