### ISSUE TITLE
TypeError factorize(db)

### ISSUE THREAD

**Issue by DBarthe** [Legilibre/legi.py#15]
Bonjour,

Je rencontre un bug en suivant les instructions du readme:
```bash
$ python -m legi.tar2sqlite legi.sqlite ./tarballs
....
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/barth/strapdata/legi.py/legi/tar2sqlite.py", line 510, in <module>
    main()
  File "/home/barth/strapdata/legi.py/legi/tar2sqlite.py", line 505, in main
    factorize(db)
TypeError: main() takes 0 positional arguments but 1 was given
```

J'utilise Python 3.5.2 et la version master de legi.py.

Le problème est simple, `factorize.main` est appelé avec `db` en paramètre depuis `tar2sqlite.main`, alors que `db` est une variable globale dans `factorize.py`. Il semblerait avoir été introduit par bc2e734b09c8c8e6bdb6c54e763a64c66b714eaa, en février... pourquoi pas programmer l'ajout de tests fonctionnels dans la roadmap ? :)

Super boulot en tout cas ! Je vais me servir de cette librairie :)

**Comment by DBarthe** [comment]
Thanks :+1:
