### ISSUE TITLE
reprise de téléchargment (resume)

### ISSUE THREAD

**Issue by revolunet** [Legilibre/legi.py#31]
Bonjour,

Déjà un grand merci pour le travail phénoménal effectué sur ce projet 💪

Je signale juste un petit souci, quand un fichier s'est mal téléchargé, apparemment le script n'arrive pas à reprendre :

```sh
265 remote files, 244 common files (1 invalid), 21 missing files
Continuing the download of the file legi_20180202-195135.tar.gz
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/legi.py/legi/download.py", line 70, in <module>
    download_legi(args.directory)
  File "/usr/src/app/legi.py/legi/download.py", line 56, in download_legi
    rest=local_files[filename]['size']
  File "/usr/local/lib/python3.6/ftplib.py", line 442, in retrbinary
    with self.transfercmd(cmd, rest) as conn:
  File "/usr/local/lib/python3.6/ftplib.py", line 399, in transfercmd
    return self.ntransfercmd(cmd, rest)[0]
  File "/usr/local/lib/python3.6/ftplib.py", line 359, in ntransfercmd
    host, port = self.makepasv()
  File "/usr/local/lib/python3.6/ftplib.py", line 337, in makepasv
    host, port = parse227(self.sendcmd('PASV'))
  File "/usr/local/lib/python3.6/ftplib.py", line 273, in sendcmd
    return self.getresp()
  File "/usr/local/lib/python3.6/ftplib.py", line 236, in getresp
    resp = self.getmultiline()
  File "/usr/local/lib/python3.6/ftplib.py", line 222, in getmultiline
    line = self.getline()
  File "/usr/local/lib/python3.6/ftplib.py", line 210, in getline
    raise EOFError
EOFError
```

En supprimant le fichier en question et en relançant la commande, ca marche bien 👌

**Comment by lel-amri** [comment]
Impossible de reproduire chez moi (gist de mon shell [python2.7](https://gist.github.com/lel-amri/88d1c1ebd5cfe5ef078cc1cbdcd6dce4) et [python3.6](https://gist.github.com/lel-amri/f2aa359415159a5f028f451ae0bc832f)).

Quelle est ta distribution ?

D'après le traceback, ça semble venir du serveur FTP qui a fermé la connexion juste après la commande 'PASV' (Ce qui est un comportement inattendu).

**Comment by revolunet** [comment]
Ok merci 

Python 3.6.4 sur docker... je réouvre si je reproduis
