### ISSUE TITLE
Erreur lors de la génération de la BDD SQLite

### ISSUE THREAD

**Issue by mouradlounas** [Legilibre/legi.py#41]
Bonjour,

Dans l'étape de génération de la BDD SQLite, j'obtiens les erreurs suivantes. Pourriez-vous m'indiquer la source de l'erreur et les dépendances qui manqueraient à mon installation?

```
(ml_data) bash-3.2$ python -m legi.tar2sqlite legi.sqlite ./tarballs
read format "cab" is not supported
read format "rar" is not supported
read format "lha" is not supported
read format "7zip" is not supported
read format "warc" is not supported
read filter "rpm" is not supported
read filter "lzip" is not supported
read filter "gzip" is not supported
read filter "uu" is not supported
read filter "grzip" is not supported
read filter "none" is not supported
read filter "compress" is not supported
read filter "lzop" is not supported
read filter "lrzip" is not supported
read filter "lzma" is not supported
read filter "lz4" is not supported
read filter "bzip2" is not supported
read filter "xz" is not supported
read filter "all" is not supported
Traceback (most recent call last):
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/mouradlounas/legi.py/legi/tar2sqlite.py", line 13, in <module>
    import libarchive
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/site-packages/libarchive/ffi.py", line 184, in <module>
    c_int, check_int)
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/ctypes/__init__.py", line 361, in __getattr__
    func = self.__getitem__(name)
  File "/Users/mouradlounas/anaconda2/envs/ml_data/lib/python3.6/ctypes/__init__.py", line 366, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7f88c9d47550, archive_read_open_filename_w): symbol not found_
```

Par avance merci,

Mourad.

**Comment by Changaco** [comment]
Tu sembles avoir une très vieille version de [libarchive](https://libarchive.org/), installer une version plus récente devrait régler le problème.

**Comment by mouradlounas** [comment]
J'ai installé une version récente mais j'ai de nouveau des erreurs. Voici la nouvelle erreur:
python -m legi.tar2sqlite legi.sqlite ./tarballs
No handlers could be found for logger "libarchive"
Traceback (most recent call last):
  File "/Users/mouradlounas/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/mouradlounas/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/mouradlounas/legifrance_project/legi.py/legi/tar2sqlite.py", line 13, in <module>
    import libarchive
  File "/Users/mouradlounas/anaconda2/lib/python2.7/site-packages/libarchive/__init__.py", line 1, in <module>
    from .entry import ArchiveEntry
  File "/Users/mouradlounas/anaconda2/lib/python2.7/site-packages/libarchive/entry.py", line 6, in <module>
    from . import ffi
  File "/Users/mouradlounas/anaconda2/lib/python2.7/site-packages/libarchive/ffi.py", line 184, in <module>
    c_int, check_int)
  File "/Users/mouradlounas/anaconda2/lib/python2.7/site-packages/libarchive/ffi.py", line 95, in ffi
    f = getattr(libarchive, 'archive_'+name)
  File "/Users/mouradlounas/anaconda2/lib/python2.7/ctypes/__init__.py", line 379, in __getattr__
    func = self.__getitem__(name)
  File "/Users/mouradlounas/anaconda2/lib/python2.7/ctypes/__init__.py", line 384, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
AttributeError: dlsym(0x7fbc0d559080, archive_read_open_filename_w): symbol not found

**Comment by mouradlounas** [comment]
Comment lui indiquer de pointer vers une version de Python et libarchive?
