### ISSUE TITLE
SQLite syntax error at runtime

### ISSUE THREAD

**Issue by semiosys** [Legilibre/legi.py#47]
Bonjour,

J'ai fait une première approche laborieuse de la base LEGI avec basex et des requêtes XQuery, et là je découvre votre projet, j'essaie de suivre les premiers pas pour explorer votre approche. 

Je teste sous Centos 7 avec Python 2.7 et j'ai une erreur d'exécution dans la phase de construction de la base. Je trouve cela plutôt étrange, l'erreur provient probablement d'ailleurs.

Si vous avez une piste pour contourner ce problème, je suis preneur ! Merci.

python -m legi.tar2sqlite legi.sqlite ./tarballs
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 556, in <module>
    main()
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 481, in main
    db = connect_db(args.db, pragmas=args.pragma)
  File "legi/utils.py", line 101, in connect_db
    db.executescript(f.read())
sqlite3.OperationalError: near "WHERE": syntax error

Pour info : 
python --version
Python 2.7.5

sudo pip install -r requirements.txt
Requirement already satisfied: libarchive-c in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 1)) (2.8)
Requirement already satisfied: lxml in /usr/lib64/python2.7/site-packages (from -r requirements.txt (line 2)) (4.2.5)
Requirement already satisfied: tqdm in /usr/lib/python2.7/site-packages (from -r requirements.txt (line 3)) (4.28.1)

sudo pip install libarchive
Requirement already satisfied: libarchive in /usr/lib/python2.7/site-packages (0.4.6)
Requirement already satisfied: nose in /usr/lib/python2.7/site-packages (from libarchive) (1.3.7)

**Comment by Changaco** [comment]
Python 2.7.5 est très obsolète (+ de 5 ans depuis sa sortie), donc il est possible que ce soit la source du problème. D'ailleurs j'ai commencé à supprimer la gestion de python 2.7 dans legi.py ce matin : #46.

**Comment by semiosys** [comment]
Ah dommage je viens de compiler la 3.26 car le package manager refuse d'installer la toute dernière version de sqlite mais je lis : "On CentOS 7, SQLite 3.7 is already installed. You can’t remove it because all the other packages of CentOS 7 depend on it. CentOS 7 don’t provide any way to update it."
En gros je suis bloqué en SQLite version 3.7.17 alors que la dernière est la 3.26 ...

**Comment by semiosys** [comment]
Chose curieuse, si je lance un seconde fois la commande  (python -m legi.tar2sqlite legi.sqlite ./tarballs), l'erreur SQLite disparaît et une nouvelle erreur liée à libarchive apparaît : 


Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 556, in <module>
    main()
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 530, in main
    process_archive(db, args.directory + '/' + archive_name, not args.skip_links)
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 194, in process_archive
    with libarchive.file_reader(archive_path) as archive:
AttributeError: 'module' object has no attribute 'file_reader'

comme si le module libarchive (installé avec pip) n'avait pas l'api attendue.
J'avais fait un:  sudo pip install libarchive
cela devrait aller non ?

ls -l /lib64/libarchive.so*
lrwxrwxrwx 1 root root     16 26 déc.  15:28 /lib64/libarchive.so -> libarchive.so.13
lrwxrwxrwx 1 root root     20 26 déc.  15:04 /lib64/libarchive.so.13 -> libarchive.so.13.1.2
-rwxr-xr-x 1 root root 688344 15 sept.  2016 /lib64/libarchive.so.13.1.2

**Comment by Changaco** [comment]
Ton premier message semble indiquer que tu as installé le module `libarchive` via `sudo pip install libarchive`, or c'est `libarchive-c` dont legi.py a besoin, et un seul de ces modules peut être installé en même temps.

`sudo pip uninstall libarchive libarchive-c && sudo pip install libarchive-c` devrait corriger ce problème.

**Comment by Changaco** [comment]
En ce qui concerne l'erreur différente la deuxième fois, c'est parce que legi.py ne détecte pas que la création de la base de données a planté au milieu et qu'il faudrait recommencer. Du coup il faut que tu supprimes le fichier toi-même (`rm legi.sqlite`).

**Comment by semiosys** [comment]
Merci pour ta prompte réponse.
la désintallation de libarchive et l'installation de libarchive-c n'a malheureusement rien changé.
je réessaierai avec python 3.
Merci
