### ISSUE TITLE
Messages d'erreur à l'éxécution  sqlite3.OperationalError: near "WHERE": syntax error

### ISSUE THREAD

**Issue by semiosys** [Legilibre/legi.py#52]
Bonjour,
j'essaie de faire tourner legy.py sur une machine Centos 7. 
Ma première tentative avec python 2.7 n'ayant pas abouti, je viens de réessayer avec : 

sqlite3
SQLite version 3.26.0 2018-12-01 12:34:55

python36 --version
Python 3.6.6

Mais j'ai des messages d'erreur.
A noter que le téléchargement des tar.gz fonctionne bien.

A la première exécution j'ai une erreur. Un fichier legi.sqlite a bien été créé.
A la seconde exécution (et les suivantes) j'ai une autre erreur.

Voici les erreurs, si nous avez une piste ... merci d'avance.

python36 -m legi.tar2sqlite legi.sqlite ./tarballs
read format "warc" is not supported
read filter "lz4" is not supported
write format "warc" is not supported
write filter "lz4" is not supported
Traceback (most recent call last):
  File "/home/develie/LEGI/legi.py/legi/utils.py", line 90, in connect_db
    db.run("SELECT 1 FROM db_meta LIMIT 1")
sqlite3.OperationalError: no such table: db_meta

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 552, in <module>
    main()
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 477, in main
    db = connect_db(args.db, pragmas=args.pragma)
  File "/home/develie/LEGI/legi.py/legi/utils.py", line 93, in connect_db
    db.executescript(f.read())
sqlite3.OperationalError: near "WHERE": syntax error

-rw-r--r-- 1 develie develie 25600  9 janv. 18:00 legi.sqlite

Nouvelle tentative (second appel):

[develie@ip80 legi.py]$ python36 -m legi.tar2sqlite legi.sqlite ./tarballs
read format "warc" is not supported
read filter "lz4" is not supported
write format "warc" is not supported
write filter "lz4" is not supported
> last_update is None
> Processing Freemium_legi_global_20180706-113123.tar.gz...
825014it [01:26, 11335.56it/s]Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 552, in <module>
    main()
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 526, in main
    process_archive(db, args.directory + '/' + archive_name, not args.skip_links)
  File "/home/develie/LEGI/legi.py/legi/tar2sqlite.py", line 267, in process_archive
    }, replace=True)
  File "/home/develie/LEGI/legi.py/legi/utils.py", line 117, in insert
    """.format(or_clause, table, keys, placeholders), values)
sqlite3.OperationalError: no such table: duplicate_files
Exception ignored in: <bound method tqdm.__del__ of 825014it [01:27, 11335.56it/s]>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 931, in __del__
    self.close()
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 1133, in close
    self._decr_instances(self)
  File "/usr/local/lib/python3.6/site-packages/tqdm/_tqdm.py", line 496, in _decr_instances
    cls.monitor.exit()
  File "/usr/local/lib/python3.6/site-packages/tqdm/_monitor.py", line 52, in exit
    self.join()
  File "/usr/lib64/python3.6/threading.py", line 1053, in join
    raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread

**Comment by Changaco** [comment]
Bizarre. Est-ce que `python -c "import sqlite3; print(sqlite3.sqlite_version)"` affiche bien `3.26.0` ?

**Comment by semiosys** [comment]
Solution trouvée (reompilation de Python 3.7 et de SQlite 3.26 depuis les dernières sources + LD_LIBRARY_PATH pour forcer le chargement le module dynamique avec la bonne version).
