### ISSUE TITLE
Échec de mise à jour

### ISSUE THREAD

**Issue by Changaco** [Legilibre/legi.py#62]
```
191 remote files, 190 common files (0 invalid), 1 missing files
Downloading the file LEGI_20190329-223156.tar.gz
=> Starting tar2sqlite...
> last_update is 20190328-214428
> Skipped 306 old archives
> Processing LEGI_20190329-223156.tar.gz...  
made 532629 changes in the database: {
    "delete from liens": 204221,
    "delete from sommaires": 45899,
    "insert into articles": 987,
    "insert into liens": 213389,
    "insert into sections": 65,
    "insert into sommaires": 47371,
    "insert into textes_structs": 19,
    "insert into textes_versions": 19,
    "update in articles": 10414,
    "update in sections": 5156,
    "update in textes_structs": 470,
    "update in textes_versions": 470,
    "upsert into duplicate_files": 4149
}
skipped 27794 files in unknown folder `eli`
textes_structs
    ('id', 'LEGITEXT000006065566')
    ('versions', '<VERSION etat=""><LIEN_TXT debut="2999-01-01" fin="2999-01-01" id="JORFTEXT000000692519" num="86-520"/></VERSION><VERSION etat="ABROGE_DIFF"><LIEN_TXT debut="1986-03-16" fin="2019-04-01" id="LEGITEXT000006065566" num="86-520"/></VERSION>')
    ('dossier', 'TNC_en_vigueur')
    ('cid', 'JORFTEXT000000692519')
    ('mtime', 1544210873)
 380.53it/s]2it [00:09, 829.26it/s]0.77it/s]52.37it/s]5it [00:31, 19.28it/s]36, 231.42it/s]it/s]0:53, 18.99it/s] 113.83it/s]/s] 42.84it/s]it/s]it [01:30, 15.12it/s]01:37, 115.77it/s]8252it [01:49, 34.46it/s]6.98it/s]/s]04, 95.89it/s]1it/s]3620it [02:14, 119.89it/s]02:19, 177.50it/s]:29, 13.84it/s]02:34, 202.32it/s]37.81it/s]s]Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "legi/tar2sqlite.py", line 556, in <module>
    main()
  File "legi/tar2sqlite.py", line 530, in main
    process_archive(db, args.directory + '/' + archive_name, not args.skip_links)
  File "legi/tar2sqlite.py", line 461, in process_archive
    suppress(get_table, db, liste_suppression)
  File "legi/tar2sqlite.py", line 119, in suppress
    db.insert(table, row)
  File "legi/utils.py", line 125, in insert
    """.format(or_clause, table, keys, placeholders), values)
sqlite3.IntegrityError: UNIQUE constraint failed: textes_structs.id
```

**Comment by Seb35** [comment]
Je constate également cela sur https://archeo-lex.fr/codes. J’ai supprimé la BDD et en ai recréé une mais ça s’arrête sur la même livraison le 29 mars 2019.

**Comment by Changaco** [comment]
Je me suis enfin penché sur ce problème, je pense avoir trouvé la cause et la solution (#65).

**Comment by Seb35** [comment]
Merci, je testerai d’ici peu. J’ai relancé les màj Archéo Lex la semaine dernière en ignorant cette exception, mais ce n’était pas propre.
